"use client";
import { useState, type ReactNode } from "react";
import Image from "next/image";
import { DEMO_PHONE_DISPLAY, DEMO_PHONE_E164 } from "@/lib/constants";
import { HOME_FAQS } from "./home-faqs";
const dollars = (n: number) => new Intl.NumberFormat("en-US", {style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
export function RevenueHome({ children }: { children: ReactNode }) {
  const [calls, setCalls] = useState(8);
  const [jobValue, setJobValue] = useState(275);
  const [bookingRate, setBookingRate] = useState(35);
  return <>{/* Marketing content is server rendered; only the calculator is interactive. */}
<a className="skip" href="#main">Skip to content</a>
<header><a className="brand" href="#top" aria-label="Missed No More Pro home"><Image className="official-logo" src="/images/mnm-official-logo-2026.png" alt="Missed No More Pro — Every call answered. Every lead captured." width={695} height={160} priority /></a><nav aria-label="Main navigation"><a href="#system">The system</a><a href="#businesses">Who we help</a><a href="#pricing">Pricing</a></nav><div className="nav-actions"><a className="signin" href="/login">Sign in</a><a className="button small" href="/signup">Start free trial <span>↗</span></a></div></header>
<main id="main"><section className="hero wrap" id="top"><div className="hero-copy"><p className="eyebrow"><span className="signal"></span> ANSWER. QUOTE. BOOK.</p><h1><span className="seo-line">AI receptionist for small service businesses</span>YOUR NEXT<br />JOB IS <span>CALLING.</span></h1><p className="hero-sub">Don’t let it become someone else’s.</p><p className="intro">You’re on a job. Your phone is ringing. Our AI receptionist answers, quotes, books, and follows up so you can keep doing what you do best.</p><div className="actions"><a className="button" href="/signup">Take control. Start free. <span>↗</span></a><a className="text-link" href="#real-call"><span className="play">▶</span> Hear a real call</a></div><p className="fine">7-day free trial · Plans from $50/mo · Card required</p></div><div className="hero-visual"><div className="art-stage" aria-hidden="true"></div><div className="call-label"><span className="signal"></span> OPPORTUNITY INCOMING <span className="mono">00:12</span></div><div className="job-ticket"><div className="ticket-top"><span>CALL → CUSTOMER</span><span className="ticket-check">✓</span></div><strong>While you were working.</strong><div className="ticket-row"><span>Call answered</span><b>✓</b></div><div className="ticket-row"><span>Customer booked</span><b>✓</b></div><div className="ticket-row"><span>Your team notified</span><b>✓</b></div><p>Illustrative workflow</p></div><div className="visual-caption">THE FRONT OFFICE THAT NEVER CLOCKS OUT.</div></div></section>
<section className="real-call wrap" id="real-call" aria-labelledby="real-call-title"><div className="real-call-copy"><p className="eyebrow"><span className="signal"></span> REAL CALL EXAMPLE</p><h2 id="real-call-title">HEAR THE AI<br /><em>HANDLE THE CALL.</em></h2><p>A stranded driver needs a tow. Listen as the AI gathers the details, confirms the destination, captures a callback number, and gives an exact price from the business’s approved rules.</p><ul><li>Actual call audio</li><li>2 minutes, 12 seconds</li><li>Captions included</li></ul></div><div className="real-call-player"><div className="player-status"><span className="signal"></span><span>AI RECEPTIONIST · ROADSIDE SERVICE</span><span>RECORDED EXAMPLE</span></div><p className="player-title">From roadside request to an exact quote.</p><audio controls preload="metadata"><source src="/audio/real-ai-receptionist-call.m4a" type="audio/mp4" /><track kind="captions" src="/audio/real-ai-receptionist-call.vtt" srcLang="en" label="English" default />Your browser does not support audio playback.</audio><details className="call-transcript"><summary>Read the call transcript</summary><p><b>Caller:</b> I’m stranded on Interstate 71 with two flat tires.</p><p><b>AI receptionist:</b> It confirms the vehicle, location, tow destination, and callback number, then returns an exact $115 quote from the business’s approved pricing rules.</p></details><p className="player-note">This example uses a roadside workflow. Your assistant follows the services, hours, prices, and handoff rules you set.</p></div></section>
<div className="service-strip"><span>SMALL TEAMS. BIG DAYS.</span><div>TOWING <i>✳</i> HVAC <i>✳</i> PLUMBING <i>✳</i> ELECTRICAL <i>✳</i> HOME SERVICES</div></div>
<section className="trust-strip wrap" aria-label="How Missed No More Pro protects your business">
<div><span className="trust-kicker">YOUR RULES</span><strong>Quotes follow the rates you approve.</strong><p>No improvised prices.</p></div>
<div><span className="trust-kicker">YOUR TEAM</span><strong>Real handoff when a person is needed.</strong><p>You set the transfer and alert rules.</p></div>
<div><span className="trust-kicker">YOUR RECORD</span><strong>Every call leaves an actionable trail.</strong><p>Calls, messages, bookings, and follow-up stay connected.</p></div>
</section>
<span id="product" /><span id="features" /><section className="pillars wrap section" id="system">
<div className="section-heading"><p className="eyebrow">01 / THE WORK YOUR PHONE SHOULD BE DOING</p><h2>THREE WAYS TO<br />KEEP BUSINESS <em>MOVING.</em></h2><p>A 24/7 AI receptionist for small service businesses.<br />Built around the moments that turn a caller into a customer.</p></div>
<div className="pillar-grid">
<article className="pillar"><span className="number">01</span><div className="pillar-visual answering"><div className="visual-head"><span>AFTER HOURS</span><span>11:47 PM</span></div><div className="wave" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div className="visual-state">✓ &nbsp; “Thanks for calling. How can I help?”</div></div><h3>Answer every call.</h3><p>On a roof. Under a hood. Off the clock. Your AI phone assistant greets callers, captures the details, and gets the conversation moving.</p><ul><li>24/7 business phone answering</li><li>Spam screening and human transfers</li><li>Missed-call text-back</li></ul></article>
<article className="pillar"><span className="number">02</span><div className="pillar-visual quote"><div className="visual-head"><span>YOUR RATES. YOUR RULES.</span><span>EXAMPLE</span></div><div className="quote-line"><span>Dispatch · Zone 2</span><b>$65</b></div><div className="quote-line"><span>Battery jump</span><b>$50</b></div><div className="quote-line"><span>After-hours service</span><b>$20</b></div><div className="quote-total"><span>Exact quote</span><b>$135<span>.00</span></b></div></div><h3>Give exact quotes.</h3><p>Your pricing should work as hard as you do. Quotes are calculated from the rates, service areas, and rules you approve.</p><ul><li>Pricing set by your business</li><li>Distance-based calculations</li><li>Uncertain requests flagged for your team</li></ul></article>
<article className="pillar"><span className="number">03</span><div className="pillar-visual booking"><div className="visual-head"><span>FROM CALL TO CALENDAR</span><span>EXAMPLE</span></div><div className="calendar-preview"><div className="date-block"><small>TODAY</small><b>2:30</b><span>PM</span></div><div><strong>Service visit</strong><span>Customer confirmed</span><span className="booked">✓ Booked</span></div></div><div className="visual-state">✓ &nbsp; Details sent to your team</div></div><h3>Book the job.</h3><p>Give customers a next step while you’ve got their attention. Your assistant checks availability, books the visit, and sends the confirmation.</p><ul><li>Booking inside your approved hours</li><li>Text confirmations and reminders</li><li>Every lead saved in your CRM</li></ul></article>
</div></section>
<span id="live-demo" /><section className="demo wrap" id="demo"><div><p className="eyebrow">HEAR YOUR NEXT HIRE.</p><h2>GIVE IT A RING.</h2><p>Ask for a price. Ask about availability. Hear our live AI receptionist demo answer as Summit Home Services.</p></div><div className="demo-action"><a href={`tel:${DEMO_PHONE_E164}`} className="demo-number">{DEMO_PHONE_DISPLAY} <span>↗</span></a><div className="actions"><a className="button dark" href={`tel:${DEMO_PHONE_E164}`}>Call the live demo <span>↗</span></a><a className="text-link" href={`sms:${DEMO_PHONE_E164}`}>Text the AI</a></div><p className="fine">No signup needed. Standard call and message rates apply.</p></div></section>
<section className="calculator-section wrap section" id="calculator"><div className="calculator-copy"><p className="eyebrow">02 / THE COST OF “I’LL CALL THEM BACK”</p><h2>HOW MUCH WORK<br />IS GETTING <em>AWAY?</em></h2><p>When a customer needs help now, waiting for a callback can mean calling the next business. Use your own numbers to see the opportunity.</p><p className="calc-note">An estimate, based on your inputs. Actual bookings and revenue will vary.</p></div><div className="calculator"><div className="control"><label htmlFor="calls">Missed calls per week</label><output id="calls-value" htmlFor="calls">{calls}</output><input id="calls" type="range" min="0" max="40" value={calls} onChange={e=>setCalls(Number(e.target.value))} /></div><div className="control"><label htmlFor="value">Average job value</label><output id="value-value" htmlFor="value">{dollars(jobValue)}</output><input id="value" type="range" min="25" max="1500" step="25" value={jobValue} onChange={e=>setJobValue(Number(e.target.value))} /></div><div className="control"><label htmlFor="rate">Percentage that could book</label><output id="rate-value" htmlFor="rate">{bookingRate}%</output><input id="rate" type="range" min="0" max="100" step="5" value={bookingRate} onChange={e=>setBookingRate(Number(e.target.value))} /></div><div className="calc-result"><span>POTENTIAL MONTHLY JOB REVENUE</span><strong id="revenue" aria-live="polite">{dollars(calls * 52 / 12 * jobValue * bookingRate / 100)}</strong><small>Missed calls × 52 ÷ 12 × job value × booking rate</small></div><a className="text-link" href="/signup">Start catching those opportunities <span>↗</span></a></div></section>
<section className="control-section section"><div className="wrap control-layout"><div><p className="eyebrow">03 / YOU’RE STILL IN THE DRIVER’S SEAT</p><h2>YOUR BUSINESS.<br />YOUR RULES.<br /><em>ONE CLEAR VIEW.</em></h2><p>Set the prices, hours, service area, and handoff rules. Missed No More Pro handles the front office around the way you work.</p><div className="support-feature"><h3>Smart CRM</h3><p>Keep call summaries, messages, customer details, and job progress together. Know who called and what happens next.</p></div><div className="support-feature"><h3>AI Business Assistant</h3><p>Ask who needs a follow-up or how the week is going. Turn your business activity into useful answers.</p></div></div><div className="command-panel"><div className="panel-bar"><span className="mini-mark" aria-hidden="true">✓</span><span>YOUR COMMAND CENTER</span><small>ILLUSTRATIVE VIEW</small></div><div className="panel-greeting"><span>One call. Every detail.</span><strong>Roadside assistance</strong><span>Incoming customer request</span></div><div className="journey"><div><span className="journey-step">01</span><p><b>Answered</b><small>Caller and location captured</small></p><span>✓</span></div><div><span className="journey-step">02</span><p><b>Quoted</b><small>Approved rates applied</small></p><span>✓</span></div><div><span className="journey-step">03</span><p><b>Booked</b><small>Calendar and customer updated</small></p><span>✓</span></div></div><div className="panel-message"><span>YOU</span><p>“Who needs a follow-up?”</p></div><div className="panel-answer"><span>AI BUSINESS ASSISTANT</span><p>Your customer history and lead pipeline, ready when you need them.</p></div></div></div></section>
<section className="businesses wrap section" id="businesses"><div className="section-heading"><p className="eyebrow">04 / MADE FOR BUSINESSES THAT SHOW UP</p><h2>YOU DO THE HARD WORK.<br />WE HELP THE WORK <em>FIND YOU.</em></h2><p>From solo operators to growing crews, your front office should keep up with your day.</p></div><div className="industry-grid"><article><span>01 / ON THE ROAD</span><h3>Towing & roadside</h3><p>Capture the location, calculate distance-based quotes, and get the request to your team.</p><a href="/ai-receptionist-for-towing">Explore AI for towing ↗</a></article><article><span>02 / ON THE JOB</span><h3>Home service pros</h3><p>HVAC, plumbing, electrical, roofing, garage doors, and appliance repair. Keep booking while your hands are full.</p><a href="/ai-receptionist-for-hvac">HVAC ↗</a> &nbsp; <a href="/ai-receptionist-for-plumbers">Plumbing ↗</a> &nbsp; <a href="/ai-receptionist-for-electricians">Electrical ↗</a> &nbsp; <a href="/ai-receptionist-for-roofers">Roofing ↗</a> &nbsp; <a href="/ai-receptionist-for-garage-door-repair">Garage doors ↗</a></article><article><span>03 / ON THE MOVE</span><h3>Everyday local services</h3><p>Cleaning, landscaping, pest control, locksmiths, handymen, and salons. Give every new inquiry a clear next step.</p><a href="/ai-receptionist-for-locksmiths">Locksmiths ↗</a> &nbsp; <a href="/ai-receptionist-for-salons">Salons ↗</a></article></div></section>
<section className="operator wrap"><div className="operator-word" aria-hidden="true">BUILT<br />FROM<br /><span>THE JOB.</span></div><div><p className="eyebrow">A SMALL BUSINESS PROBLEM. A SMALL BUSINESS ORIGIN.</p><h2>WE KNOW WHAT<br />A MISSED CALL COSTS.</h2><p>Missed No More Pro started with an operator who was tired of missing calls. The system runs on a real roadside-assistance business: answering, quoting, booking, and texting customers.</p><p>Now we’re bringing that same front office to small service businesses, with founding customers helping shape what comes next.</p><a className="text-link" href="/about">Meet Missed No More Pro ↗</a><p className="fine">Live pilot. Verified customer outcomes will be published as they become available.</p></div></section>
<section className="testimonials wrap section" id="feedback"><div className="section-heading"><p className="eyebrow">EARLY FEEDBACK</p><h2>WHAT BUSINESS OWNERS<br />ARE <em>SAYING</em> ABOUT<br />MISSED NO MORE PRO.</h2><p>Not paid endorsements. Reactions from real business owners who tried a live demo of the AI receptionist.</p></div><div className="testimonial-grid">
<article className="testimonial"><p className="stars" aria-label="5 out of 5 stars">★★★★★</p><p className="quote">“The AI assistant made booking incredibly easy, but what really caught my attention was that it gave me an actual, straightforward price quote during the conversation. I didn’t even realize an AI receptionist could do that. The entire experience was smooth and genuinely impressive. I’d highly recommend checking out Missed No More Pro.”</p><div className="testimonial-who"><b>Tom S.</b><span>Cleveland, OH · Demo Feedback</span></div></article>
<article className="testimonial"><p className="stars" aria-label="5 out of 5 stars">★★★★★</p><p className="quote">“I run a small local service business, and most days I’m out in the field working by myself. Having something like Missed No More Pro answering my calls would mean I wouldn’t have to stop what I’m doing, climb down a ladder, or risk missing a potential customer just because I couldn’t get to the phone. As my business grows, this is absolutely something I could see myself paying for.”</p><div className="testimonial-who"><b>Frank G.</b><span>Independence, OH · Business Owner Feedback</span></div></article>
<article className="testimonial"><p className="stars" aria-label="5 out of 5 stars">★★★★★</p><p className="quote">“I’d heard a lot about AI receptionists for businesses, but I was always skeptical about how well they actually worked. After hearing Missed No More Pro handle a call, I was impressed by how natural and smooth the entire process was. It can answer calls, handle intake, book appointments, and the built-in CRM really stood out to me. Running a salon, it always seems like the phone rings at the exact moment I can’t answer it. I’m seriously considering using Missed No More Pro very soon.”</p><div className="testimonial-who"><b>Jennifer K.</b><span>Parma, OH · Demo Feedback</span></div></article>
</div></section>
<div className="existing-pricing">{children}</div>
<section className="faq wrap section" id="faq"><div><p className="eyebrow">THE DETAILS THAT MATTER</p><h2>GOOD QUESTIONS.<br /><em>STRAIGHT ANSWERS.</em></h2><a className="text-link" href="/ai-phone-assistant">Read the AI phone assistant guide ↗</a></div><div className="faq-list">{HOME_FAQS.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</div></section>
<section className="final-cta"><div className="wrap"><p className="eyebrow">ANSWER EVERY CALL. EXACT QUOTES. BOOKED JOBS.</p><h2>LET YOUR NEXT CALL<br />BE YOUR <span>NEXT JOB.</span></h2><div className="actions"><a className="button" href="/signup">Start your 7-day free trial <span>↗</span></a><a className="text-link" href={`tel:${DEMO_PHONE_E164}`}>Call the demo first ↗</a></div><p className="fine">Plans from $50/mo. Card required. Cancel before your trial ends to avoid charges.</p></div></section>
</main><footer className="wrap"><div className="footer-main"><a className="brand" href="#top"><Image className="official-logo" src="/images/mnm-official-logo-2026.png" alt="Missed No More Pro — Every call answered. Every lead captured." width={695} height={160} priority /></a><p>The AI front office for small service businesses.<br />Answer. Quote. Book.</p><a href="mailto:hello@missednomorepro.com">hello@missednomorepro.com</a></div><div className="footer-links"><div><b>EXPLORE</b><a href="#system">AI receptionist</a><a href="#pricing">Plans & pricing</a><a href="/industries">Industries we serve</a><a href="/about">Our story</a><a href="/changelog">What’s new</a></div><div><b>LEARN</b><a href="/ai-answering-service">AI answering service</a><a href="/ai-phone-assistant">AI phone assistant guide</a><a href="/vs/virtual-receptionist">AI vs. virtual receptionist</a><a href="/vs/answering-service">Compare answering services</a></div><div><b>THE DETAILS</b><a href="/privacy">Privacy policy</a><a href="/terms">Terms of service</a><a href="/sms-terms">SMS terms</a><a href="/login">Sign in</a></div></div><div className="footer-bottom"><span>© 2026 Missed No More Pro</span><span>BUILT FOR THE WORK AHEAD.</span></div></footer>
</>;
}
