-- ════════════════════════════════════════════════════════════════
-- Ph14a + Ph14b: the last two add-ons.
--   * Call Intelligence (+$19, `call_intelligence`): a weekly in-app
--     Insights report computed from existing call/lead/job data + a short
--     LLM digest. Stored in insight_reports; generated by the daily cron
--     on a weekly (Monday) gate so we stay within Vercel Hobby's 2 crons.
--   * Reputation Manager (+$29, `reputation_manager`): SMS review requests
--     with a reputation gate (rate 1-5 by text; 4-5 → public review link,
--     1-3 → private feedback to the owner). Tracked in reviews.
--
-- Conventions: tenant_id + RLS (members read; server writes), composite
-- FKs, explicit grants. No new external service — reuses OPENAI_API_KEY,
-- Twilio SMS, and businesses.gbp_url for the Google review link. GBP-API
-- auto-replies + emailed reports are deferred (need Google verification /
-- Resend) — note in the UI.
-- ════════════════════════════════════════════════════════════════

-- ── insight_reports (Call Intelligence) ────────────────────────
create table public.insight_reports (
  id           uuid primary key default gen_random_uuid(),
  tenant_id    uuid not null references public.organizations (id) on delete cascade,
  business_id  uuid,
  kind         text not null default 'call_intelligence'
               check (kind in ('call_intelligence')),
  period_start timestamptz not null,
  period_end   timestamptz not null,
  payload      jsonb not null default '{}'::jsonb,
  created_at   timestamptz not null default now(),
  foreign key (business_id, tenant_id)
    references public.businesses (id, tenant_id) on delete set null
);

create index insight_reports_tenant_time_idx
  on public.insight_reports (tenant_id, created_at desc);

-- ── reviews (Reputation Manager) ───────────────────────────────
create table public.reviews (
  id                uuid primary key default gen_random_uuid(),
  tenant_id         uuid not null references public.organizations (id) on delete cascade,
  business_id       uuid,
  contact_id        uuid,
  job_id            uuid,
  rating            int check (rating between 1 and 5),
  -- requested -> rated (>=4, public link sent) | feedback (<=3, awaiting/has
  -- private feedback). Routed to the owner, never auto-posted publicly.
  status            text not null default 'requested'
                    check (status in ('requested', 'rated', 'feedback')),
  feedback_redacted text,
  public_url_sent   boolean not null default false,
  created_at        timestamptz not null default now(),
  rated_at          timestamptz,
  foreign key (business_id, tenant_id)
    references public.businesses (id, tenant_id) on delete set null,
  foreign key (contact_id, tenant_id)
    references public.contacts (id, tenant_id) on delete set null
);

create index reviews_tenant_time_idx on public.reviews (tenant_id, created_at desc);
create index reviews_contact_status_idx on public.reviews (contact_id, status);

-- ── reputation settings on sms_settings (per business) ─────────
alter table public.sms_settings
  add column reputation_enabled     boolean not null default false,
  add column review_facebook_url    text,
  add column review_request_template text not null default
    'Thanks for choosing {business}, {name}! How did we do? Reply 1-5 (5 = great). Reply STOP to opt out.';

-- ── RLS ────────────────────────────────────────────────────────
alter table public.insight_reports enable row level security;
alter table public.reviews enable row level security;

create policy "members read their insight reports"
  on public.insight_reports for select to authenticated
  using (app.is_member(tenant_id));
create policy "members read their reviews"
  on public.reviews for select to authenticated
  using (app.is_member(tenant_id));

-- Both are server-written (cron + the SMS webhook via service role).
grant select, insert, update, delete on public.insight_reports, public.reviews to service_role;
grant select on public.insight_reports to authenticated;
grant select on public.reviews to authenticated;
